### ISSUE TITLE
Berrycam express install

### ISSUE THREAD

**Issue by bersal** [pitography/BerryCamExpress#6]
I have cloned the node js and other packages in the Berrrycamexpress directory but I do not get a response to node -v command What do I need to do to make it work? Thank you for your guidance

**Comment by stevies** [comment]
Get the latest stable node.js package available from the node-arm site:
```
pi@raspberry ~ $ wget http://node-arm.herokuapp.com/node_latest_armhf.deb
```
After downloading the package, install it:
```
pi@raspberry ~ $ sudo dpkg -i node_latest_armhf.deb
```
This takes a while so be patient... once it finishes, verify it's installed:
```
pi@raspberry ~ $ node -v
```

Taken from here:  http://www.andrewconnell.com/blog/setup-node-js-on-raspberry-pi-2-b

**Comment by stevies** [comment]
I have a newer version of this app here: 

https://github.com/stevies/berrycam-aurelia

It is still work in progress, but it is a lot nicer if you are wanting to actually play around with the code and it uses a much more up-to-date JavaScript framework - Aurelia - http://aurelia.io

**Comment by bersal** [comment]
Thank you. Can I clone the BerryCam Aurelia on my earlier clone of the BerryCamExpress? any potential problems?

**Comment by stevies** [comment]
They are individual projects.  You should clone to separate directories / git repositories.

**Comment by bersal** [comment]
Thank you for your advice. I did get the latest node.js package and now I have node version 4.2.1 and npm version 2.14.7. When I run npm install command I get the following warnings
npm WARN package.json BerryCamExpress@0.0.4 No repository field.
npm WARN package.json BerryCamExpress@0.0.4 No license field.
Although I do have the license sub directory in the BerryCamExpress directory. 
What am I doing wrong? Thank you for your assistance. Also the Dist directory did not install Is this due to the warnings? I have attached a copy in MS word of the screen 
[Copy of screen.docx](https://github.com/pitography/BerryCamExpress/files/41627/Copy.of.screen.docx)

**Comment by stevies** [comment]
Those are warnings, not errors - should not affect the BerryCam installation.  However, I think none of this will have been tested with node v4.x.  If it does not work, go back to using node 0.12.7 or something older like that.

**Comment by bersal** [comment]
Thank you
I am a noobie How do I go back to node 0.12.7? Do I need also an older version of npm? I have currently npm v 
2.14.7



Date: Mon, 23 Nov 2015 07:01:47 -0800

**Comment by stevies** [comment]
For modifying the version of node/npm you have installed, see: https://davidwalsh.name/nvm

**Comment by bersal** [comment]
Than you again
To run the sever on the berrycamexpress server your  instructions say cd to dist. But I could find the dist directory.  Did it noe install when Iran the npm install command? How do I get the dsit dirctory to install? 

Date: Mon, 23 Nov 2015 07:01:47 -0800

**Comment by stevies** [comment]
Did you run:
<code>grunt pi </code>
from inside the BerryCamExpress directory?
That should create the /dist directory.

**Comment by bersal** [comment]
Sorry for being such a pest. Thank you again for your patience and guidance. Iran grunt pi from the BerryCamExpress directory but I gor an error message The screen is as below

pi@raspberrypi ~ $ cd BerryCamExpress
pi@raspberrypi ~/BerryCamExpress $ grunt pi
-bash: grunt: command not found
pi@raspberrypi ~/BerryCamExpress $ cd grunt
-bash: cd: grunt: No such file or directory
pi@raspberrypi ~/BerryCamExpress $ ls
app         Gruntfile.js  node_modules  README.md  TODO.md
bower.json  LICENSE       package.json  test
pi@raspberrypi ~/BerryCamExpress $ grunt
-bash: grunt: command not found
pi@raspberrypi ~/BerryCamExpress $

Date: Mon, 23 Nov 2015 12:50:37 -0800

**Comment by stevies** [comment]
No problem. 

If you get error "grunt: command not found" - that means you have not installed grunt.  You need to go back and follow all the instructions from the beginning - looks like you have missed some steps.  

<code>sudo npm install -g grunt-cli </code>

**Comment by bersal** [comment]
Thank you so very much. I finally was able to run the berrycam server and take pictures from my PC. However do I need to run "grunt pi" each time I start the server? Is this due to the error message I get which is 



pi@raspberrypi ~/BerryCamExpress $ grunt pi

Loading "npm-install.js" tasks...ERROR

>> Error: Cannot find module 'npmlog'
If so how do I correct the error . Thank you again





Date: Tue, 24 Nov 2015 12:28:57 -0800

**Comment by stevies** [comment]
You only need to run <code>grunt pi</code> to build the project once.
