### ISSUE TITLE
Installation on Jessie?

### ISSUE THREAD

**Issue by jditte** [pitography/BerryCamExpress#7]
Has the installation been tested on Jessie? The phantomjs installation has been failing for me...

**Comment by stevies** [comment]
Sorry, I don't know what Jessie is.

**Comment by jditte** [comment]
It's the latest Raspbian release (released in very late September).

**Comment by stevies** [comment]
Not tested with that version.  Sorry.


-------- Original message --------

**Comment by jditte** [comment]
Would you mind testing it and updating instructions if necessary? Or has anybody already installed it successfully on Jessie? Thanks!

**Comment by stevies** [comment]
When you say 'phantomjs installation has been failing' - what errors are you getting?  At what stage of the build?

Phantomjs is a headless browser used for testing. So it is safe to remove if you just want to build and run the app.  I'm not even sure that the build is using phantomjs anywhere.  But maybe I've forgotten where it is included. 

If you can't isolate phantomjs, I can only suggest that you revert back to an older version of the operating system.

**Comment by stevies** [comment]
I see that phantomjs is brought in indirectly by Jasmine.  You should see something like this when it is installing: 

> phantomjs@1.9.19 install /home/steve/WebstormProjects/BerryCamExpress/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
> node install.js
>
PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
  [=======================================-] 98% 0.0s
Received 12854K total.
Extracting tar contents (via spawned process)
Removing /home/steve/WebstormProjects/BerryCamExpress/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1449164445270/phantomjs-1.9.8-linux-x86_64 -> /home/steve/WebstormProjects/BerryCamExpress/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/steve/WebstormProjects/BerryCamExpress/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm WARN installMany normalize-package-data was bundled with npm@1.3.26, but bundled package wasn't found in unpacked tree
grunt-contrib-copy@0.5.0 node_modules/grunt-contrib-copy
>

If that stage fails - maybe there is no binary suitable for the latest pi operating system - then you'll need to remove all references to jasmine from the package.json file.  
>
    "grunt-contrib-jasmine": "~0.5.3",
    "grunt-template-jasmine-requirejs": "0.1.10",
>
That might break some of the build files, so then you'll need to hunt down anything that is broken and remove it.

**Comment by stevies** [comment]
You should be OK just removing the above lines from package.json and running

<code> npm install </code>

again.  

Then, before you run 

<code>grunt pi</code>

you will need to delete or comment out lines 160 to 250 of Gruntfile.js - that removes the jasmine tests that would need phantomjs.

Hope this helps. 


        //jasmine: {
        //
        //    coverage: {
        //        src: '<%= conf.app %>/scripts/**/*.js',
        //
        //        options: {
        //            specs: [
        //                '<%= conf.test %>/spec/**/*.spec.js'
        //            ],
        //            keepRunner: true,
        //
        //            vendor: '<%= conf.vendor %>',
        //
        //            helpers: [
        //                '<%= conf.test %>/spec/helpers/*-helper.js'
        //            ],
        //
        //            template: require('grunt-template-jasmine-istanbul'),
        //
        //            templateOptions: {
        //                coverage: '<%= conf.bin.coverage %>/coverage.json',
        //                report: [
        //                    {
        //                        type: 'html',
        //                        options: {
        //                            dir: '<%= conf.bin.coverage %>/html'
        //                        }
        //                    },
        //                    {
        //                        type: 'text-summary'
        //                    },
        //                    {
        //                        type: 'cobertura',
        //                        options: {
        //                            dir: '<%= conf.bin.coverage %>/cobertura'
        //                        }
        //                    }
        //                ],
        //                // 1. don't replace src for the mixed-in template with instrumented sources
        //                replace: false,
        //                template: require('grunt-template-jasmine-requirejs'),
        //                templateOptions: {
        //
        //                    requireConfigFile: '<%= conf.app %>/scripts/main.js',
        //                    requireConfig: {
        //
        //                        paths: '<%= conf.requireConfigPaths %>',
        //
        //                        // 2. use the baseUrl you want
        //                        baseUrl: '<%= conf.app %>/scripts',
        //
        //                        // 3. pass requirePaths of the sources being instrumented as a configuration option
        //                        //    these paths should be the same as the jasmine task's src
        //                        //    unfortunately, grunt.config.get() doesn't work because the config
        //                        //    is just being evaluated
        //                        config: {
        //                            instrumented: {
        //                                src: grunt.file.expand('app/scripts/**/*.js')
        //                            }
        //                        },
        //                        // 4. use this callback to read the paths of the sources being instrumented and
        //                        //    redirect requests to them appropriately
        //                        callback: function () {
        //                            define('instrumented', ['module'], function (module) {
        //                                return module.config().src;
        //                            });
        //                            require(['instrumented'], function (instrumented) {
        //                                var oldLoad = requirejs.load;
        //                                requirejs.load = function (context, moduleName, url) {
        //                                    // normalize paths
        //                                    if (url.substring(0, 1) === '/') {
        //                                        url = url.substring(1);
        //                                    } else if (url.substring(0, 2) === './') {
        //                                        url = url.substring(2);
        //                                    }
        //                                    // redirect
        //                                    if (instrumented.indexOf(url) > -1) {
        //                                        url = '.grunt/grunt-contrib-jasmine/' + url;
        //                                    }
        //                                    return oldLoad.apply(this, [context, moduleName, url]);
        //                                };
        //                            });
        //
        //                            jasmine.getJSONFixtures().fixturesPath = 'test/spec/fixtures/json';
        //                        }
        //                    }
        //                }
        //            }
        //        }
        //    }
        //},

**Comment by jditte** [comment]
Thanks a lot for the help and sorry for not being able to get back to you earlier. I have been able to build BerryCamExpress with the proposed modifications.

**Comment by stevies** [comment]
OK.  Glad it worked.  I'll put a note on the main page to point to this for anyone using Jessie.

**Comment by cwayllace** [comment]
Hello Stevies:

I am trying to install it in the latest version of Pi, but when it is installing de project dependencies npm install it gives me the error 

 Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/stevies/node-raspicam.git
npm ERR! 
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/stevies/node-raspicam.git/'
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-06-18T01_56_25_491Z-debug.log


Could you help me please? 
or is it a new version of the project?
Could you guide me please?

**Comment by stevies** [comment]
> Hello Stevies:
> 
> I am trying to install it in the latest version of Pi, but when it is installing de project dependencies npm install it gives me the error
> 
> Error while executing:
> npm ERR! /usr/bin/git ls-remote -h -t https://github.com/stevies/node-raspicam.git
> npm ERR!
> npm ERR! remote: Invalid username or password.
> npm ERR! fatal: Authentication failed for 'https://github.com/stevies/node-raspicam.git/'
> npm ERR!
> npm ERR! exited with error code: 128
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/pi/.npm/_logs/2020-06-18T01_56_25_491Z-debug.log
> 
> Could you help me please?
> or is it a new version of the project?
> Could you guide me please?

Hi.  I am sorry, but I appear to have removed my fork of node-raspicam when tidying up my github.  You can perhaps change the package link to:

https://github.com/troyth/node-raspicam

or install that package and remove mine.

`npm i raspicam`

Maybe the original package has fixed the problem that meant I had to fork it.  If I remember correctly, then the issue was very minor, so even if not fixed, you shouldn't have too much trouble forking and fixing it yourself.  If I can help, let me know.

**Comment by stevies** [comment]
As far as I can tell, the original node-raspicam code has now fixed the problem that made me fork it.  See:  https://github.com/troyth/node-raspicam/commit/ac820ff43e4570c315fd764ea348cc5383c3fc24

I may not have time to update the berrycam project any time soon, so you may just want to fix the import yourself.  

Let me know if that does not fix things.
